# Generated by Django 5.2 on 2026-09-13 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_authtokenmodel_token_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtokenmodel',
            name='created',
        ),
        migrations.AddField(
            model_name='authtokenmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authtokenmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dogusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
