# Generated by Django 5.2 on 2026-09-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_barkmodel_sniff_count_usersniffmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
